#!/usr/bin/env bash
# Provision a new isolated WordPress site (local files + optional Portainer deploy).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$SCRIPT_DIR/_lib.sh"

require_cmd openssl python3

usage() {
  cat <<EOF
Usage: $0 --slug SLUG --domain DOMAIN [options]

Required:
  --slug SLUG              lowercase site id (letters, numbers, hyphens)
  --domain DOMAIN          public hostname (e.g. acme.orija.store)

Optional:
  --title TITLE            WordPress site title (default: SLUG)
  --tagline TEXT           tagline
  --admin-user USER        WP admin username (default: admin)
  --admin-email EMAIL      WP admin email (default: admin@DOMAIN)
  --admin-password PASS    WP admin password (default: generated)
  --host-port PORT         host origin port (default: next free in registry)
  --notes TEXT             freeform note in registry
  --deploy                 create/redeploy Portainer stack after writing files
  --force                  overwrite existing sites/<slug>/.env
  -h, --help               show this help

Examples:
  $0 --slug acme --domain acme.orija.store --title "Acme Co" --deploy
  $0 --slug clientb --domain clientb.orija.store --admin-user clientbadmin --deploy
EOF
}

SLUG=""
DOMAIN=""
TITLE=""
TAGLINE="Managed by Orija WordPress Hosting"
ADMIN_USER="admin"
ADMIN_EMAIL=""
ADMIN_PASSWORD=""
HOST_PORT=""
NOTES=""
DEPLOY=0
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slug) SLUG="$2"; shift 2 ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    --title) TITLE="$2"; shift 2 ;;
    --tagline) TAGLINE="$2"; shift 2 ;;
    --admin-user) ADMIN_USER="$2"; shift 2 ;;
    --admin-email) ADMIN_EMAIL="$2"; shift 2 ;;
    --admin-password) ADMIN_PASSWORD="$2"; shift 2 ;;
    --host-port) HOST_PORT="$2"; shift 2 ;;
    --notes) NOTES="$2"; shift 2 ;;
    --deploy) DEPLOY=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

[[ -n "$SLUG" && -n "$DOMAIN" ]] || { usage; exit 1; }
slug_ok "$SLUG" || { echo "Invalid slug: $SLUG (use lowercase a-z0-9-)" >&2; exit 1; }
TITLE="${TITLE:-$SLUG}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(rand_password 28)}"
MYSQL_PASSWORD="$(rand_password 28)"
MYSQL_ROOT_PASSWORD="$(rand_password 32)"

# Ensure PyYAML available for registry ops
python3 -c 'import yaml' 2>/dev/null || pip3 install --user pyyaml >/dev/null

SITE_DIR="$ROOT_DIR/sites/$SLUG"
ENV_FILE="$SITE_DIR/.env"
CREDS_FILE="$SITE_DIR/credentials.txt"

if registry_has_slug "$SLUG" && [[ "$FORCE" -ne 1 ]]; then
  echo "Site slug already in registry: $SLUG (use --force to overwrite local env)" >&2
  exit 1
fi
if [[ -f "$ENV_FILE" && "$FORCE" -ne 1 ]]; then
  echo "Env already exists: $ENV_FILE (use --force)" >&2
  exit 1
fi

HOST_PORT="${HOST_PORT:-$(next_free_port)}"

mkdir -p "$SITE_DIR"
umask 077
cat >"$ENV_FILE" <<EOF
# Generated by provision-site.sh — DO NOT COMMIT
SITE_SLUG=$SLUG
SITE_DOMAIN=$DOMAIN
SITE_TITLE=$TITLE
SITE_TAGLINE=$TAGLINE
HOST_PORT=$HOST_PORT

MYSQL_DATABASE=wordpress
MYSQL_USER=wordpress
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
WORDPRESS_TABLE_PREFIX=wp_

WP_ADMIN_USER=$ADMIN_USER
WP_ADMIN_PASSWORD=$ADMIN_PASSWORD
WP_ADMIN_EMAIL=$ADMIN_EMAIL

WP_MEMORY_LIMIT=256M
WP_MAX_MEMORY_LIMIT=512M
EOF

cat >"$CREDS_FILE" <<EOF
WordPress site credentials — store in your password manager, then delete this file.
===============================================================================
Stack:          wp-$SLUG
Domain:         https://$DOMAIN
Origin port:    $HOST_PORT  (Cloudflare Tunnel → http://localhost:$HOST_PORT)
WP admin URL:   https://$DOMAIN/wp-admin
WP username:    $ADMIN_USER
WP password:    $ADMIN_PASSWORD
WP email:       $ADMIN_EMAIL
DB name/user:   wordpress / wordpress
DB password:    $MYSQL_PASSWORD
DB root pass:   $MYSQL_ROOT_PASSWORD
Generated:      $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

export SITE_SLUG="$SLUG" SITE_DOMAIN="$DOMAIN" SITE_TITLE="$TITLE" \
  HOST_PORT="$HOST_PORT" WP_ADMIN_USER="$ADMIN_USER" WP_ADMIN_EMAIL="$ADMIN_EMAIL" \
  SITE_STATUS="provisioned" SITE_NOTES="$NOTES"
upsert_registry_site >/dev/null

echo_ok "Provisioned site files for $SLUG"
echo_info "Env:         $ENV_FILE"
echo_info "Credentials: $CREDS_FILE"
echo_info "Registry:    $REGISTRY"
echo_info "Host port:   $HOST_PORT"
echo_info "Tunnel map:  $DOMAIN → http://localhost:$HOST_PORT"

if [[ "$DEPLOY" -eq 1 ]]; then
  "$SCRIPT_DIR/deploy-site.sh" "$SLUG"
else
  echo_info "Next: map the tunnel, then run: ./scripts/deploy-site.sh $SLUG"
fi
