import {
  Adjustments,
  DEFAULT_ADJUSTMENTS,
  Preset,
} from '../types/adjustments';

function preset(
  id: string,
  name: string,
  group: string,
  patch: Partial<Adjustments>,
): Preset {
  return {
    id,
    name,
    group,
    source: 'builtin',
    adjustments: { ...DEFAULT_ADJUSTMENTS, ...patch },
  };
}

/** Curated built-in presets — values tuned to read clearly on mobile */
export const BUILTIN_PRESETS: Preset[] = [
  preset('original', 'Original', 'Basics', {}),
  preset('natural', 'Natural', 'Basics', {
    exposure: 0.25,
    contrast: 15,
    shadows: 22,
    vibrance: 18,
    clarity: 10,
  }),
  preset('vivid', 'Vivid', 'Basics', {
    contrast: 35,
    highlights: -25,
    shadows: 18,
    vibrance: 55,
    saturation: 22,
    clarity: 28,
    dehaze: 12,
  }),
  preset('matte', 'Matte', 'Film', {
    contrast: -18,
    highlights: -30,
    shadows: 35,
    blacks: 42,
    whites: -15,
    saturation: -12,
    clarity: -10,
    grain: 10,
  }),
  preset('fade', 'Fade', 'Film', {
    contrast: -22,
    blacks: 48,
    whites: -18,
    highlights: -15,
    saturation: -22,
    temperature: 12,
    grain: 14,
  }),
  preset('warm-glow', 'Warm Glow', 'Color', {
    exposure: 0.3,
    temperature: 55,
    tint: 12,
    shadows: 22,
    vibrance: 28,
    highlights: -18,
    saturation: 8,
  }),
  preset('cool-steel', 'Cool Steel', 'Color', {
    temperature: -48,
    tint: -8,
    contrast: 28,
    highlights: -30,
    clarity: 32,
    dehaze: 18,
    vibrance: 10,
  }),
  preset('golden-hour', 'Golden Hour', 'Color', {
    exposure: 0.35,
    temperature: 62,
    tint: 16,
    highlights: -35,
    shadows: 28,
    vibrance: 32,
    saturation: 10,
    clarity: 8,
  }),
  preset('moody', 'Moody', 'Drama', {
    exposure: -0.45,
    contrast: 38,
    highlights: -55,
    shadows: -15,
    blacks: -28,
    clarity: 38,
    dehaze: 28,
    vibrance: -8,
    saturation: -5,
  }),
  preset('punch', 'Punch', 'Drama', {
    contrast: 45,
    clarity: 48,
    dehaze: 22,
    vibrance: 40,
    highlights: -35,
    shadows: 22,
    saturation: 12,
  }),
  preset('soft-portrait', 'Soft Portrait', 'Portrait', {
    exposure: 0.3,
    highlights: -40,
    shadows: 35,
    whites: -12,
    clarity: -28,
    texture: -22,
    vibrance: 14,
    temperature: 16,
  }),
  preset('bw-classic', 'B&W Classic', 'B&W', {
    saturation: -100,
    contrast: 32,
    highlights: -22,
    shadows: 16,
    clarity: 24,
    grain: 18,
  }),
  preset('bw-highkey', 'B&W High Key', 'B&W', {
    saturation: -100,
    exposure: 0.75,
    contrast: -8,
    highlights: -12,
    shadows: 48,
    whites: 32,
    blacks: 18,
  }),
  preset('cinematic', 'Cinematic', 'Drama', {
    exposure: -0.2,
    contrast: 28,
    highlights: -48,
    shadows: 16,
    temperature: -12,
    tint: 14,
    saturation: -15,
    vibrance: 10,
    clarity: 18,
    dehaze: 14,
  }),
];
