import {
  Adjustments,
  DEFAULT_ADJUSTMENTS,
  Preset,
} from '../types/adjustments';

function preset(
  id: string,
  name: string,
  group: string,
  patch: Partial<Adjustments>,
): Preset {
  return {
    id,
    name,
    group,
    source: 'builtin',
    adjustments: { ...DEFAULT_ADJUSTMENTS, ...patch },
  };
}

/** Curated built-in presets inspired by common Lightroom looks */
export const BUILTIN_PRESETS: Preset[] = [
  preset('original', 'Original', 'Basics', {}),
  preset('natural', 'Natural', 'Basics', {
    exposure: 0.15,
    contrast: 8,
    shadows: 12,
    vibrance: 10,
    clarity: 5,
  }),
  preset('vivid', 'Vivid', 'Basics', {
    contrast: 20,
    highlights: -15,
    shadows: 10,
    vibrance: 35,
    saturation: 12,
    clarity: 15,
  }),
  preset('matte', 'Matte', 'Film', {
    contrast: -10,
    highlights: -20,
    shadows: 25,
    blacks: 30,
    whites: -10,
    saturation: -8,
    clarity: -5,
  }),
  preset('fade', 'Fade', 'Film', {
    contrast: -15,
    blacks: 40,
    whites: -15,
    highlights: -10,
    saturation: -15,
    temperature: 8,
  }),
  preset('warm-glow', 'Warm Glow', 'Color', {
    exposure: 0.2,
    temperature: 35,
    tint: 8,
    shadows: 15,
    vibrance: 15,
    highlights: -10,
  }),
  preset('cool-steel', 'Cool Steel', 'Color', {
    temperature: -30,
    tint: -5,
    contrast: 18,
    highlights: -20,
    clarity: 20,
    dehaze: 10,
  }),
  preset('golden-hour', 'Golden Hour', 'Color', {
    exposure: 0.25,
    temperature: 45,
    tint: 12,
    highlights: -25,
    shadows: 20,
    vibrance: 20,
    saturation: 5,
  }),
  preset('moody', 'Moody', 'Drama', {
    exposure: -0.35,
    contrast: 25,
    highlights: -40,
    shadows: -10,
    blacks: -20,
    clarity: 25,
    dehaze: 20,
    vibrance: -5,
  }),
  preset('punch', 'Punch', 'Drama', {
    contrast: 30,
    clarity: 35,
    dehaze: 15,
    vibrance: 25,
    highlights: -25,
    shadows: 15,
  }),
  preset('soft-portrait', 'Soft Portrait', 'Portrait', {
    exposure: 0.2,
    highlights: -30,
    shadows: 25,
    whites: -10,
    clarity: -20,
    texture: -15,
    vibrance: 8,
    temperature: 10,
  }),
  preset('bw-classic', 'B&W Classic', 'B&W', {
    saturation: -100,
    contrast: 20,
    highlights: -15,
    shadows: 10,
    clarity: 15,
    grain: 12,
  }),
  preset('bw-highkey', 'B&W High Key', 'B&W', {
    saturation: -100,
    exposure: 0.6,
    contrast: -5,
    highlights: -10,
    shadows: 40,
    whites: 25,
    blacks: 15,
  }),
  preset('cinematic', 'Cinematic', 'Drama', {
    exposure: -0.15,
    contrast: 15,
    highlights: -35,
    shadows: 10,
    temperature: -8,
    tint: 10,
    saturation: -10,
    vibrance: 5,
    clarity: 10,
    dehaze: 8,
  }),
];
